name: Docker Image CI

# This action runs on every push to the 'main' branch
on:
  push:
    branches: [ "main" ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set repo name to lowercase
        id: string
        run: echo "repo_name=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ steps.string.outputs.repo_name }}:latest
            ghcr.io/${{ steps.string.outputs.repo_name }}:${{ github.sha }}
          build-args: |
            NEXT_PUBLIC_POCKETBASE_URL=${{ secrets.NEXT_PUBLIC_POCKETBASE_URL }}
            NEXT_PUBLIC_SHOP_LATITUDE=${{ secrets.NEXT_PUBLIC_SHOP_LATITUDE }}
            NEXT_PUBLIC_SHOP_LONGITUDE=${{ secrets.NEXT_PUBLIC_SHOP_LONGITUDE }}